version: '3.3'
services:
  web: 
    image: aakashgaur57/apache_ka_code
    container_name: akweb
    ports:
      - "2233:80"
    volumes:
      - ./apache/:/var/www/html/
  myweb:
    build: ./apache/.
    image: mynewIMG
    container_name: myakweb
    ports:
      - "2244:80"
    volumes:
      - ./apache/:/var/www/html/
    networks:
      - jecrc
networks:
  jecrc:
   external: true
